name: EFEL - Update stack version in terraform on package release

on:
  push:
    branches:
      - 'main'

jobs:
  promote:
    name: promote
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.EL_B2C_BOT_TOKEN }}

    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          same-branch-only: false
          abort-after-seconds: 300


      - name: get package information
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "SHA_HASH=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "STACK_NAME=${GITHUB_REPOSITORY##*stack-}" >> $GITHUB_ENV


      - name: dispatch promotion event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ env.BOT_TOKEN }}
          repository: oliverdon/dispatcher
          event-type: promote-stack
          client-payload: '{"repository": "${{ env.REPO_NAME }}", "stack": "${{ env.STACK_NAME }}", "sha": "${{ env.SHA_HASH }}"}'



